steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', '-b', 'main', 'https://github.com/ncolossi/cdf-cicd.git']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=cdfbuild-sa-key > cdfbuild-sa-keyfile.json' ]
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud auth activate-service-account --key-file cdfbuild-sa-keyfile.json' ]
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud auth print-access-token > access-token.txt' ]
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:
     - '-c'
     - |
       git diff-tree --no-commit-id --name-only -r $COMMIT_SHA
       for FILE in datafusion/pipelines/*.json
       do
       echo Deploying $$FILE
       CURRFILE=$(echo $$FILE | sed "s/.*\///" | cut -f 1 -d '.')
       curl -X PUT -H "Authorization: Bearer $(cat access-token.txt)" "https://cdf-demo-analytics-demo-ngc-dot-usc1.datafusion.googleusercontent.com/api/v3/namespaces/prod/apps/$$CURRFILE" -d "@./datafusion/pipelines/$$CURRFILE.json"
       done
